(deftheme ample-light
  "Created 2014-09-30.")

(custom-theme-set-faces
 'ample-light
 '(cursor ((t (:foreground "#DBD9C1" :background "#F57E00"))))
 '(fringe ((t (:background "#CBC9B1"))))
 '(region ((t (:background "#BBB9A1"))))
 '(font-lock-builtin-face ((t (:foreground "#528FD1"))))
 '(font-lock-comment-face ((t (:foreground "#959595"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#959595"))))
 '(font-lock-function-name-face ((t (:foreground "#4A8F30"))))
 '(font-lock-keyword-face ((t (:foreground "#4170B3"))))
 '(font-lock-string-face ((t (:foreground "#5D5C01"))))
 '(font-lock-preprocessor-face ((t (:foreground "#FF8512"))))
 '(font-lock-type-face ((t (:foreground "#CD5542"))))
 '(font-lock-constant-face ((t (:foreground "#9B55C3"))))
 '(font-lock-warning-face ((t (:foreground "red" :bold t))))
 '(font-lock-variable-name-face ((t (:foreground "#787800"))))
 '(font-lock-doc-face ((t (:foreground "#7D7C21"))))
 '(powerline-active1 ((t (:foreground "#252525"))))
 '(mode-line-inactive ((t (:background "#ABA991" :foreground "#DBD9C1"))))
 '(mode-line ((t (:background "#BBB9A1" :foreground "gray43"))))
 '(linum ((t (:background nil :foreground "#959595"))))
 '(popup-tip-face ((t (:background "#ABA991" :foreground "#7D7C21"))))
 '(header-line ((t (:background "gray43" :foreground "#DBD9C1"))))
 '(button ((t (:foreground "#68A5E9" :background nil :underline t))))
 '(isearch ((t (:background "#4170B3" :foreground "#DBD9C1"))))
 '(lazy-highlight ((t (:background "#DBD9C1" :foreground "#9B55C3" :underline t))))
 '(ace-jump-face-background ((t (:inherit font-lock-comment-face :background nil))))
 '(ace-jump-face-foreground ((t (:foreground "#9B55C3" :bold t :background nil))))
 '(vertical-border ((t (:background "#757575" :foreground "#252525"))))
 '(hl-line ((t (:background "#E2E0C1"))))
 '(minibuffer-prompt ((t (:foreground "#9B55C3" :bold t :background nil))))
 '(compilation-error ((t (:foreground "#CD5542" :bold t))))
 '(compilation-warning ((t (:foreground "#FF8512" :bold t))))
 '(compilation-info ((t (:foreground "#4A8F30" :bold t))))
 '(eshell-prompt ((t (:foreground "#9B55C3"))))
 '(eshell-ls-directory ((t (:foreground "#4170B3"))))
 '(eshell-ls-product ((t (:foreground "#FF8512"))))
 '(eshell-ls-backup ((t (:foreground "#757575"))))
 '(eshell-ls-executable ((t (:foreground "#4A8F30"))))
 '(comint-highlight-prompt ((t (:foreground "#4A8F30"))))
 '(erc-nick-default-face ((t (:foreground "#4170B3"))))
 '(erc-my-nick-face ((t (:foreground "#787800"))))
 '(erc-current-nick-face ((t (:foreground "#528FD1"))))
 '(erc-notice-face ((t (:inherit font-lock-comment-face))))
 '(erc-input-face ((t (:foreground "gray43" :background nil :underline nil :box nil))))
 '(erc-timestamp-face ((t (:foreground "#757575"))))
 '(erc-prompt-face ((t (:foreground "#191919" :background "#9B55C3"))))
 '(undo-tree-visualizer-active-branch-face ((t (:inherit default))))
 '(undo-tree-visualizer-default-face ((t (:inherit font-lock-comment-face))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#787800" :background nil))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#CD5542" :background nil))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#9B55C3" :background nil))))
 '(show-paren-match ((t (:foreground nil :background "#959595"))))
 '(show-paren-mismatch ((t (:inherit error))))
 '(error ((t (:foreground "red"))))
 '(ido-only-match ((t (:foreground "#4A8F30"))))
 '(ido-first-match ((t (:foreground "#4170B3"))))
 '(ido-incomplete-regexp ((t (:foreground "#CD5542"))))
 '(ido-subdir ((t (:foreground "#787800"))))
 '(js2-external-variable ((t (:foreground "#FF8512" :background nil))))
 '(js2-function-param ((t (:foreground "#057F40" :background nil))))
 '(js2-instance-member ((t (:foreground "#9B55C3" :background nil))))
 '(js2-jsdoc-html-tag-delimiter ((t (:foreground "#959595" :background nil))))
 '(js2-jsdoc-html-tag-name ((t (:foreground "#252525" :background nil))))
 '(js2-jsdoc-tag ((t (:foreground "#9D2512" :background nil))))
 '(js2-jsdoc-type ((t (:foreground "#CD5542" :background nil))))
 '(js2-jsdoc-value ((t (:foreground "#5D5C01" :background nil))))
 '(js2-private-function-call ((t (:foreground "#057F40" :background nil))))
 '(js2-private-member ((t (:foreground "#7D7C21" :background nil))))
 '(js2-warning ((t (:foreground nil :background nil :underline "#FF8512"))))
 '(web-mode-block-attr-name-face ((t (:foreground "#8fbc8f" :background nil))))
 '(web-mode-block-attr-value-face ((t (:inherit font-lock-string-face))))
 '(web-mode-block-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-block-control-face ((t (:inherit font-lock-preprocessor-face))))
 '(web-mode-block-delimiter-face ((t (:inherit font-lock-preprocessor-face))))
 '(web-mode-block-face ((t (:foreground nil :background "LightYellow1"))))
 '(web-mode-block-string-face ((t (:inherit font-lock-string-face))))
 '(web-mode-builtin-face ((t (:inherit font-lock-builtin-face))))
 '(web-mode-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-comment-keyword-face ((t (:foreground nil :background nil :bold t))))
 '(web-mode-constant-face ((t (:foreground "#9B55C3" :background nil))))
 '(web-mode-css-at-rule-face ((t (:foreground "#9B55C3" :background nil))))
 '(web-mode-css-color-face ((t (:foreground "#528FD1" :background nil))))
 '(web-mode-css-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-css-function-face ((t (:foreground "#528FD1" :background nil))))
 '(web-mode-css-priority-face ((t (:foreground "#528FD1" :background nil))))
 '(web-mode-css-property-name-face ((t (:inherit font-lock-variable-name-face))))
 '(web-mode-css-pseudo-class-face ((t (:foreground "#528FD1" :background nil))))
 '(web-mode-css-selector-face ((t (:foreground "#4170B3" :background nil))))
 '(web-mode-css-string-face ((t (:foreground "#5D5C01" :background nil))))
 '(web-mode-current-element-highlight-face ((t (:foreground nil :background "#000000"))))
 '(web-mode-doctype-face ((t (:inherit font-lock-doc-face))))
 '(web-mode-error-face ((t (:inherit error))))
 '(web-mode-folded-face ((t (:foreground nil :background nil :underline t))))
 '(web-mode-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(web-mode-function-name-face ((t (:inherit font-lock-function-name-face))))
 '(web-mode-html-attr-custom-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-html-attr-equal-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-html-attr-name-face ((t (:inherit font-lock-keyword-face))))
 '(web-mode-html-attr-value-face ((t (:inherit font-lock-string-face))))
 '(web-mode-html-tag-bracket-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-html-tag-custom-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-html-tag-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-javascript-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-javascript-string-face ((t (:inherit font-lock-string-face))))
 '(web-mode-json-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-json-context-face ((t (:foreground "orchid3" :background nil))))
 '(web-mode-json-key-face ((t (:foreground "plum" :background nil))))
 '(web-mode-json-string-face ((t (:inherit font-lock-string-face))))
 '(web-mode-keyword-face ((t (:inherit font-lock-keyword-face))))
 '(web-mode-param-name-face ((t (:foreground "Snow3" :background nil))))
 '(web-mode-part-comment-face ((t (:inherit font-lock-comment-face))))
 '(web-mode-part-face ((t (:foreground nil :background "LightYellow1"))))
 '(web-mode-part-string-face ((t (:inherit font-lock-string-face))))
 '(web-mode-preprocessor-face ((t (:inherit font-lock-preprocessor-face))))
 '(web-mode-string-face ((t (:inherit font-lock-string-face))))
 '(web-mode-symbol-face ((t (:foreground "gold" :background nil))))
 '(web-mode-type-face ((t (:inherit font-lock-type-face))))
 '(web-mode-variable-name-face ((t (:inherit font-lock-variable-name-face))))
 '(web-mode-warning-face ((t (:inherit font-lock-warning-face))))
 '(web-mode-whitespace-face ((t (:foreground nil :background "DarkOrchid4"))))
 '(helm-M-x-key ((t (:foreground "#FF8512" :underline nil))))
 '(helm-candidate-number ((t (:foreground "#4A8F30" :background "#757575"))))
 '(helm-ff-directory ((t (:foreground "#4170B3"))))
 '(helm-ff-executable ((t (:foreground "#4A8F30"))))
 '(helm-ff-file ((t (:inherit default))))
 '(helm-ff-prefix ((t (:foreground "#CD5542"))))
 '(helm-header ((t (:foreground "#DBD9C1" :background "gray43"))))
 '(helm-match ((t (:foreground "gray43" :background "#BBC8A1"))))
 '(helm-selection ((t (:foreground "#CD5542" :background "#BBC8A1" :bold t))))
 '(helm-source-header ((t (:foreground "#252525" :background "#ABA991"))))
 '(jabber-activity-face ((t (:inherit font-lock-variable-name-face :bold t))))
 '(jabber-activity-personal-face ((t (:inherit font-lock-function-name-face :bold t))))
 '(jabber-chat-error ((t (:inherit error :bold t))))
 '(jabber-chat-text-foreign ((t (:inherit font-lock-function-name-face))))
 '(jabber-chat-text-local ((t (:inherit font-lock-keyword-face))))
 '(jabber-roster-user-away ((t (:inherit font-lock-string-face))))
 '(jabber-roster-user-chatty ((t (:foreground "#FF8512" :background nil :bold t))))
 '(jabber-roster-user-error ((t (:inherit error))))
 '(jabber-roster-user-offline ((t (:inherit font-lock-comment-face))))
 '(jabber-roster-user-online ((t (:inherit font-lock-keyword-face :bold t))))
 '(jabber-roster-user-xa ((t (:inherit font-lock-doc-face))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#81B0E3" :background nil))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#A5A5A5" :background nil))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#6190C3" :background nil))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#959595" :background nil))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#4170A3" :background nil))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#757575" :background nil))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#81B0E3" :background nil))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#A5A5A5" :background nil))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#6190C3" :background nil))))
 '(rainbow-delimiters-unmatched-face ((t (:inherit error))))
 '(ac-candidate-face ((t (:foreground "#DBD9C1" :background "#ABA991"))))
 '(ac-selection-face ((t (:foreground "#4170B3" :background "#ABA991"))))
 '(ac-candidate-mouse-face ((t (:inherit ac-selection-face))))
 '(ac-clang-candidate-face ((t (:inherit ac-candidate-face))))
 '(ac-clang-selection-face ((t (:inherit ac-selection-face))))
 '(ac-completion-face ((t (:inherit font-lock-comment-face :underline t))))
 '(ac-gtags-candidate-face ((t (:inherit ac-candidate-face))))
 '(ac-gtags-selection-face ((t (:inherit ac-selection-face))))
 '(ac-slime-menu-face ((t (:inherit ac-candidate-face))))
 '(ac-slime-selection-face ((t (:inherit ac-selection-face))))
 '(ac-yasnippet-candidate-face ((t (:inherit ac-candidate-face))))
 '(ac-yasnippet-selection-face ((t (:inherit ac-selection-face))))
 '(company-preview-common ((t (:inherit font-lock-comment-face))))
 '(company-scrollbar-bg ((t (:foreground nil :background "gray43"))))
 '(company-scrollbar-fg ((t (:foreground nil :background "#959595"))))
 '(company-tooltip ((t (:foreground "#DBD9C1" :background "#ABA991"))))
 '(company-tooltip-common ((t (:foreground "#528FD1" :background "#ABA991"))))
 '(company-tooltip-common-selection ((t (:foreground "#DBD9C1" :background "#BBB9A1"))))
 '(company-tooltip-mouse ((t (:foreground nil :background "#CAB9A1"))))
 '(company-tooltip-selection ((t (:foreground "gray43" :background "#ABA991"))))
 '(w3m-bold ((t (:foreground "#4170B3" :background nil :bold t))))
 '(w3m-current-anchor ((t (:foreground nil :background nil :underline t :bold t))))
 '(w3m-italic ((t (:foreground "#FF8512" :background nil :underline t))))
 '(w3m-underline ((t (:foreground "#4A8F30" :background nil :underline t))))
 '(ediff-current-diff-A ((t (:foreground nil :background "#CAB9A1"))))
 '(ediff-current-diff-B ((t (:foreground nil :background "#BBC8A1"))))
 '(ediff-current-diff-C ((t (:foreground nil :background "#BBB9B1"))))
 '(ediff-even-diff-A ((t (:foreground nil :background "#ABA991"))))
 '(ediff-even-diff-B ((t (:foreground nil :background "#ABA991"))))
 '(ediff-even-diff-C ((t (:foreground nil :background "#ABA991"))))
 '(ediff-fine-diff-A ((t (:foreground "gray43" :background "#CD5542"))))
 '(ediff-fine-diff-B ((t (:foreground "gray43" :background "#4A8F30"))))
 '(ediff-fine-diff-C ((t (:foreground "gray43" :background "#4170B3"))))
 '(ediff-odd-diff-A ((t (:foreground nil :background "#ABA991"))))
 '(ediff-odd-diff-B ((t (:foreground nil :background "#ABA991"))))
 '(ediff-odd-diff-C ((t (:foreground nil :background "#ABA991"))))
 '(diff-added ((t (:foreground nil :background "#BBC8A1"))))
 '(diff-changed ((t (:foreground nil :background "#BBB9B1"))))
 '(diff-removed ((t (:foreground nil :background "#CAB9A1"))))
 '(diff-context ((t (:foreground "gray43" :background nil))))
 '(diff-file-header ((t (:foreground "#DBD9C1" :background "#ABA991" :bold t))))
 '(diff-function ((t (:foreground "#DBD9C1" :background "#ABA991"))))
 '(diff-header ((t (:foreground "#DBD9C1" :background "#ABA991"))))
 '(diff-hunk-header ((t (:foreground "#DBD9C1" :background "#ABA991"))))
 '(diff-index ((t (:foreground "#DBD9C1" :background "#ABA991"))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-indicator-changed ((t (:inherit diff-changed))))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(diff-nonexistent ((t (:foreground "gray43" :background "grey70"))))
 '(diff-refine-added ((t (:foreground "gray43" :background "#4A8F30"))))
 '(diff-refine-changed ((t (:foreground "gray43" :background "#4170B3"))))
 '(diff-refine-removed ((t (:foreground "gray43" :background "#CD5542"))))
 '(Man-overstrike ((t (:foreground "#4170B3"))))
 '(Man-underline ((t (:foreground "#787800"))))
 '(org-done ((t (:foreground "#4A8F30" :background nil))))
 '(org-todo ((t (:foreground "#CD5542" :background nil))))
 '(org-hide ((t (:foreground "#DBD9C1" :background nil))))
 '(message-cited-text ((t (:inherit font-lock-comment-face))))
 '(message-header-cc ((t (:foreground "#528FD1" :background nil :bold t))))
 '(message-header-name ((t (:foreground "#FF8512" :background nil))))
 '(message-header-newsgroups ((t (:foreground "#7D7C21" :background nil :bold t))))
 '(message-header-other ((t (:foreground "#4170B3" :background nil))))
 '(message-header-subject ((t (:foreground "#5D5C01" :background nil))))
 '(message-header-to ((t (:foreground "#787800" :background nil :bold t))))
 '(message-header-xheader ((t (:foreground "#9B55C3" :background nil))))
 '(message-mml ((t (:foreground "#7D7C21" :background nil))))
 '(gnus-button ((t (:foreground nil :background nil :bold t))))
 '(gnus-cite-1 ((t (:foreground "light blue" :background nil))))
 '(gnus-cite-10 ((t (:foreground "plum1" :background nil))))
 '(gnus-cite-11 ((t (:foreground "turquoise" :background nil))))
 '(gnus-cite-2 ((t (:foreground "light cyan" :background nil))))
 '(gnus-cite-3 ((t (:foreground "light yellow" :background nil))))
 '(gnus-cite-4 ((t (:foreground "light pink" :background nil))))
 '(gnus-cite-5 ((t (:foreground "pale green" :background nil))))
 '(gnus-cite-6 ((t (:foreground "beige" :background nil))))
 '(gnus-cite-7 ((t (:foreground "orange" :background nil))))
 '(gnus-cite-8 ((t (:foreground "magenta" :background nil))))
 '(gnus-cite-9 ((t (:foreground "violet" :background nil))))
 '(gnus-cite-attribution ((t (:foreground nil :background nil))))
 '(gnus-emphasis-bold ((t (:foreground nil :background nil :bold t))))
 '(gnus-emphasis-bold-italic ((t (:foreground nil :background nil :bold t))))
 '(gnus-emphasis-highlight-words ((t (:foreground "yellow" :background "black"))))
 '(gnus-emphasis-italic ((t (:foreground nil :background nil))))
 '(gnus-emphasis-strikethru ((t (:foreground nil :background nil))))
 '(gnus-emphasis-underline ((t (:foreground nil :background nil :underline t))))
 '(gnus-emphasis-underline-bold ((t (:foreground nil :background nil :underline t :bold t))))
 '(gnus-emphasis-underline-bold-italic ((t (:foreground nil :background nil :underline t :bold t))))
 '(gnus-emphasis-underline-italic ((t (:foreground nil :background nil :underline t))))
 '(gnus-group-mail-1 ((t (:foreground "#4170B3" :background nil :bold t))))
 '(gnus-group-mail-1-empty ((t (:foreground "#4170B3" :background nil))))
 '(gnus-group-mail-2 ((t (:foreground "#68A5E9" :background nil :bold t))))
 '(gnus-group-mail-2-empty ((t (:foreground "#68A5E9" :background nil))))
 '(gnus-group-mail-3 ((t (:foreground "#528FD1" :background nil :bold t))))
 '(gnus-group-mail-3-empty ((t (:foreground "#528FD1" :background nil))))
 '(gnus-group-mail-low ((t (:foreground "#787800" :background nil :bold t))))
 '(gnus-group-mail-low-empty ((t (:foreground "#787800" :background nil))))
 '(gnus-group-news-1 ((t (:foreground "PaleTurquoise" :background nil :bold t))))
 '(gnus-group-news-1-empty ((t (:foreground "PaleTurquoise" :background nil))))
 '(gnus-group-news-2 ((t (:foreground "turquoise" :background nil :bold t))))
 '(gnus-group-news-2-empty ((t (:foreground "turquoise" :background nil))))
 '(gnus-group-news-3 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-3-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-4 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-4-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-5 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-5-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-6 ((t (:foreground nil :background nil :bold t))))
 '(gnus-group-news-6-empty ((t (:foreground nil :background nil))))
 '(gnus-group-news-low ((t (:foreground "DarkTurquoise" :background nil :bold t))))
 '(gnus-group-news-low-empty ((t (:foreground "DarkTurquoise" :background nil))))
 '(gnus-header-content ((t (:inherit message-header-other))))
 '(gnus-header-from ((t (:inherit message-header-other))))
 '(gnus-header-name ((t (:inherit message-header-name))))
 '(gnus-header-newsgroups ((t (:inherit message-header-newsgroups))))
 '(gnus-header-subject ((t (:inherit message-header-subject))))
 '(gnus-server-agent ((t (:foreground "PaleTurquoise" :background nil :bold t))))
 '(gnus-server-closed ((t (:foreground "LightBlue" :background nil))))
 '(gnus-server-denied ((t (:foreground "pink" :background nil :bold t))))
 '(gnus-server-offline ((t (:foreground "yellow" :background nil :bold t))))
 '(gnus-server-opened ((t (:foreground "green1" :background nil :bold t))))
 '(gnus-signature ((t (:foreground nil :background nil))))
 '(gnus-splash ((t (:foreground "#cccccc" :background nil))))
 '(gnus-summary-cancelled ((t (:foreground "yellow" :background "black"))))
 '(gnus-summary-high-ancient ((t (:foreground "SkyBlue" :background nil :bold t))))
 '(gnus-summary-high-read ((t (:foreground "PaleGreen" :background nil :bold t))))
 '(gnus-summary-high-ticked ((t (:foreground "pink" :background nil :bold t))))
 '(gnus-summary-high-undownloaded ((t (:foreground "LightGray" :background nil :bold t))))
 '(gnus-summary-high-unread ((t (:foreground nil :background nil :bold t))))
 '(gnus-summary-low-ancient ((t (:foreground "SkyBlue" :background nil))))
 '(gnus-summary-low-read ((t (:foreground "PaleGreen" :background nil))))
 '(gnus-summary-low-ticked ((t (:foreground "pink" :background nil))))
 '(gnus-summary-low-undownloaded ((t (:foreground "LightGray" :background nil))))
 '(gnus-summary-low-unread ((t (:foreground nil :background nil))))
 '(gnus-summary-normal-ancient ((t (:inherit default))))
 '(gnus-summary-normal-read ((t (:foreground "#4A8F30" :background nil))))
 '(gnus-summary-normal-ticked ((t (:foreground "#FF8512" :background nil))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "#959595" :background nil))))
 '(gnus-summary-normal-unread ((t (:foreground "#528FD1" :background nil))))
 '(gnus-summary-selected ((t (:foreground nil :background nil :underline t))))
 '(twittering-timeline-footer-face ((t (:foreground nil :background nil :inherit font-lock-function-name-face))))
 '(twittering-timeline-header-face ((t (:foreground nil :background nil :inherit font-lock-function-name-face))))
 '(twittering-uri-face ((t (:foreground nil :background nil :underline t))))
 '(twittering-username-face ((t (:foreground nil :background nil :inherit font-lock-keyword-face :underline t))))
 '(whitespace-empty ((t (:foreground "#959595" :background "gray70"))))
 '(whitespace-hspace ((t (:foreground "#959595" :background "grey71"))))
 '(whitespace-indentation ((t (:foreground "#959595" :background "gray72"))))
 '(whitespace-line ((t (:foreground "#9B55C3" :background nil))))
 '(whitespace-newline ((t (:foreground "#959595" :background nil))))
 '(whitespace-space ((t (:foreground "#959595" :background nil))))
 '(whitespace-space-after-tab ((t (:foreground "#959595" :background "gray73"))))
 '(whitespace-space-before-tab ((t (:foreground "#959595" :background "gray74"))))
 '(whitespace-tab ((t (:foreground "#959595" :background "grey75"))))
 '(whitespace-trailing ((t (:foreground "#959595" :background "#DBD9C1" :bold t))))
 '(magit-branch ((t (:foreground "#FF8512" :background nil))))
 '(magit-diff-add ((t (:foreground nil :background "#BBC8A1"))))
 '(magit-diff-del ((t (:foreground nil :background "#CAB9A1"))))
 '(magit-diff-file-header ((t (:foreground "gray43" :background "#BBB9A1" :bold t))))
 '(magit-diff-hunk-header ((t (:foreground "gray43" :background "#BBB9B1"))))
 '(magit-diff-merge-current ((t (:foreground "#FF8512" :background nil))))
 '(magit-diff-merge-diff3-separator ((t (:foreground "#FF8512" :background nil))))
 '(magit-diff-merge-proposed ((t (:foreground "#FF8512" :background nil))))
 '(magit-diff-merge-separator ((t (:foreground "#FF8512" :background nil))))
 '(magit-diff-none ((t (:foreground "gray43" :background nil))))
 '(magit-header ((t (:foreground "#4170B3" :background nil))))
 '(magit-item-highlight ((t (:foreground nil :background "#ABA991"))))
 '(magit-key-mode-button-face ((t (:foreground "#528FD1" :background nil))))
 '(magit-key-mode-header-face ((t (:foreground "#4170B3" :background nil))))
 '(magit-log-author ((t (:foreground "#CD5542" :background nil))))
 '(magit-log-author-date-cutoff ((t (:foreground "#CD5542" :background nil :bold t))))
 '(magit-log-date ((t (:foreground nil :background nil))))
 '(magit-log-graph ((t (:foreground "grey80" :background nil))))
 '(magit-log-sha1 ((t (:foreground "#9B55C3" :background nil))))
 '(magit-section-title ((t (:foreground "#4170B3" :background nil))))
 '(magit-tag ((t (:foreground "#4170B3" :background nil))))
 '(magit-whitespace-warning-face ((t (:foreground "#DBD9C1" :background "#9B55C3" :bold t))))
 '(git-gutter:deleted ((t (:foreground "#CD5542" :background nil :bold t))))
 '(git-gutter:modified ((t (:foreground "#9B55C3" :background nil :bold t))))
 '(git-gutter:separator ((t (:foreground "#FF8512" :background nil :bold t))))
 '(git-gutter:unchanged ((t (:foreground "#7D7C21" :background nil))))
 '(highlight-indentation-current-column-face ((t (:foreground nil :background "#E2E0C1"))))
 '(highlight-indentation-face ((t (:foreground nil :background "#ABA991"))))
 '(trailing-whitespace ((t (:background "white" :bold t))))
 '(default ((t (:foreground "gray43" :background "#DBD9C1")))))

(provide-theme 'ample-light)
